// license-header java merge-point
// Generated by andromda-jsf cartridge (utils\AutocompleteHelper.java.vsl) DO NOT EDIT!
package com.wim;

import java.util.Map;
import javax.el.MethodExpression;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

public class AutocompleteHelper {

    public String callComplete(MethodExpression completeMethod, String queryParamName){
        final FacesContext facesContext=FacesContext.getCurrentInstance();
        final Map<String,String> parameters = facesContext.getExternalContext().getRequestParameterMap();
        final Object fieldValue = parameters.get(queryParamName);
        final String stringValue=fieldValue==null?"":fieldValue.toString();

        ((HttpServletRequest)facesContext.getExternalContext().getRequest()).setAttribute("autocompleteResult", completeMethod.invoke(FacesContext.getCurrentInstance().getELContext(), new Object[]{stringValue}));
        return null;
    }
}